### ISSUE TITLE
[Error]: no me esta mostrando en las historia clinica la valoracion inicial 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#10]
### ¿Qué sucedió?

al paciente en la 1era sesion se le diligencia la valoracion fisioterapeutica pero cuando se realiza a partir de la 2da sesion no se visualiza la informacion previamente guardada 

### Pasos para reproducir

https://github.com/user-attachments/assets/535f6dc6-369d-4046-94fc-3ff70ac1712a

### Versión

1.3.220

**Comment by CJavierSaldana** [comment]
Para las siguientes sesiones se está tomando la información llenada de la primera sesión. Entonces el fisio al llenar la sesión verá la información que también llenó de la primera sesión precargada en  cada una de las partes de terapia integral

**Comment by mifisicoltda** [comment]
sigue sin mostrarme la info de la valoracion, adjunto video 
https://github.com/user-attachments/assets/cb92e488-cfcd-42c2-9923-e9abc6452c55
gracias

**Comment by CJavierSaldana** [comment]
en la siguiente sesión de ese paciente en específico no habrá problema y se precargará la información. con los pacientes cuya información ya fue guardada no se veran afectados hasta la siguiente sesión.

**Comment by mifisicoltda** [comment]
Revisado y aprobado
