### ISSUE TITLE
[Funcionalidad]: añadir opciones en ocupacion

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#13]
### ¿Tu solicitud está relacionada con algún problema?

me hace falta unos parametros de escogencia en el campo de ocupacion

### Describe la solución que te gustaría

añadir estudiante, pensionado o NA dentro de las opciones de seleccion

**Comment by CJavierSaldana** [comment]
migración aplicada a producción 20241105160052_nuevas-ocupaciones

**Comment by mifisicoltda** [comment]
revisado y aprobado
