### ISSUE TITLE
[Error]: no se encuentran algunos pacientes de medicina deportiva del mes de septiembre 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#14]
### ¿Qué sucedió?

se iban a facturar los pacientes de medicina deportiva y cuando se fue al dia de la atencion que son el 20 y 21 de septiembre no se encontro la informacion en el sistema de los siguientes pacientes: 
Del día 20 de septiembre me faltan los siguientes pacientes: 
N: 22418613 cecilia marin 
N: 32700009 rosana ulloque
N:  1043344595 violeta martinez 
N: 22518277 lina Rodriguez 
N: 1046709684 sebastian lache 

Del 21 de septiembre: 
8731233 winnis castro 
1140830040 Julian carbonell 
22735361 lorena marimon 
1042259906 jimena ortiz 
1044219580 jerónimo Rodriguez 
1140903964 Luciano velasquez 
1042254401 juan duarte

### Pasos para reproducir

.

### Versión

1.3.220

**Comment by CJavierSaldana** [comment]
hablando con el doctor, que se creen los pacientes de nuevo para que los recibos aparezcan a esa persona

**Comment by CJavierSaldana** [comment]
se restauró los pacientes usando los logs de las bases de datos del 21 y 22.
