### ISSUE TITLE
[Funcionalidad]: añadir un objetivo en la hc de acondicionamiento

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#16]
### ¿Tu solicitud está relacionada con algún problema?

me hace falta un objetivo 
### Describe la solución que te gustaría

se pide añadir el objetivo de disminuir grasa corporal

**Comment by CJavierSaldana** [comment]
la opcion actualmente existe 

![image](https://github.com/user-attachments/assets/d6cdae5b-762d-46bf-b0dd-f89285526f01)

**Comment by mifisicoltda** [comment]
revisado y aprobado
