### ISSUE TITLE
[Error]: corregir el orden de los items de medicina deportiva

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#17]
### ¿Qué sucedió?

el orden en el que  se evaluan los puntos no es el correcto, 

### Pasos para reproducir
favor guiarse del formato 
[MEDICINA DEPORTIVA.xlsx](https://github.com/user-attachments/files/17564573/MEDICINA.DEPORTIVA.xlsx)

tambien se pueden guiar del formato de exportacion 
[ejemplos de exportacion medicina deportiva.pdf](https://github.com/user-attachments/files/17564579/ejemplos.de.exportacion.medicina.deportiva.pdf)

### Versión

1.3.220

**Comment by mifisicoltda** [comment]
Después del ítem de valoración inicial va el ítem completo de revisión por sistemas, después va ítem de deportivo, después el de antecedentes, después el de examen fisico, paraclínicos, diagnósticos, plan

**Comment by CJavierSaldana** [comment]
se agregó la area mencionada y se reorganizaron los campos como se menciona

**Comment by mifisicoltda** [comment]
![image](https://github.com/user-attachments/assets/3ba7a3cb-42e2-4231-9d47-ee2ee861f75b)
ese campo no debería ir 
![image](https://github.com/user-attachments/assets/c0294a1f-e736-4abd-8dbc-5ebcdf3b55e9)
se debe eliminar estos campos
