### ISSUE TITLE
[Funcionalidad]: cambiar el codigo cups de medicina deportiva 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#18]
### ¿Tu solicitud está relacionada con algún problema?
el codigo de medicina deportiva esta errado

![image](https://github.com/user-attachments/assets/3e914b8f-5a96-4947-b355-66fae1817146)

### Describe la solución que te gustaría

cambiar el código cups de 931001 a 890261 que es código de consulta de medicina deportiva.

**Comment by CJavierSaldana** [comment]
actualmente para sesiones de medicina deportiva nuevas el código CUPS es establecido correctamente. Sí se tiene un paciente en específico que tiene un CUP incorrecto, por favor crear un tiquete nuevo mencionando cambio de CUPs

![image](https://github.com/user-attachments/assets/318c3c28-8a3a-40a5-909e-afb1fa93747e)

**Comment by mifisicoltda** [comment]
revisado y aprobado
