### ISSUE TITLE
[Error]: error en la apertura de la HC vieja 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#21]
### ¿Qué sucedió?

se procede a abrir la hc de la paciente cc: 22443311 y muestra un mensaje que informa que hc v1 no es compatible con la hc v2 y cuando se quiere regresar a la pestaña anterior no muestra la pestaña de la hc v1 

### Pasos para reproducir

Uploading WhatsApp Video 2024-10-30 at 6.14.42 AM.mp4…

### Versión

1.3.220

**Comment by CJavierSaldana** [comment]
no se puede realizar triage. por favor @mifisicoltda , cargar el vídeo de nuevo. El tiquete de enviado sin permitir que el vídeo cargara completamente.

**Comment by mifisicoltda** [comment]
https://github.com/user-attachments/assets/05cd2eca-f62d-4e32-90de-595ed534af07

**Comment by CJavierSaldana** [comment]
![image](https://github.com/user-attachments/assets/c883f1b1-2db6-4d05-94e2-a1f4d5b1a703)

Están usando una Orden del año pasado del usuario. Deben crear una orden nueva e informarme para cambiarla por base de datos.

**Comment by CJavierSaldana** [comment]
Se procede a cerrar tiquete.
