### ISSUE TITLE
[Error]: se esta modificando una informacion de hc de una evolucion de egreso y no guarda correctamente 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#24]
### ¿Qué sucedió?

se esta intentando modificar un egreso del paciente el dia 30 de octubre a las 7am  identificado con cc: 72003421 pedro luzardo el  cual cuando se ingresa una informacion que es la siguiente: FINALIZA SESIONES CON BUENA  EVOLUCION Y RESPUESTA AL TRATAMIENTO. 
ARCOS DE MOVILIDAD FUNCIONALES EXTENSION 0° FLEXION 135° 
NIVELES DE FUERZA 4/5 RECTO ANTERIOR, GLUTEO MEDIO 3+/5, CORE 3+/5, GEMELOS 4/5
ENFASIS EN LA REEDUCACION DE LAS FASES DE LA MARCHA CON PLATILLOS Y VECTORES DE FUERZA. 
CONTROL NEUROMUSUCLAR Y PROPIOCEPCION  

no la guarda correctamente 

### Pasos para reproducir

se adjunta el siguiente video como ruta 

https://github.com/user-attachments/assets/bad24c0b-b483-45ee-9873-7faf16d554a5

### Versión

1

**Comment by mifisicoltda** [comment]
la version es la 1.3.220

**Comment by CJavierSaldana** [comment]
trata de hacer una modificación sin valores como los siguientes: 3+/5, CORE 3+/5, GEMELOS 4/5
revisa sí sin enviar caracteres especiales guarda correctamente . puede ser un error por los caracteres especiales.

**Comment by mifisicoltda** [comment]
lo intente guarde sin los caracteres especiales y cuando lo descargo sigue sin mostrar la informacion que le ingrese

**Comment by CJavierSaldana** [comment]
Luego de revisar el código. No refiere error, simplemente el sistema no soporta que se modifique el elemento luego de que se ha guardado. 

Esto ha aplicado así siempre. 

Sí el fisioterapeuta quiere un nuevo valor para ese paciente en específico, crear un nuevo tiquete con la información en específico para esa historia clínica. Adjuntar #orde y #sesion para hacer el cambio manualmente en la base de datos. 

La historia clínica V1 está fuera modificaciones nuevas y esto no es un error, es una nueva característica.
