### ISSUE TITLE
[Error]: desactivar la sesion de una paciente 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#25]
### ¿Qué sucedió?

se activo el dia 31 de octubre a las 6am en el espacio c2 a la paciente cc: 32740313 VERENICE DE JESUS VITTA GONZALEZ en un servicio equivocado era de articulo ortopedico y lo colocaron como terapia fisica, por lo cual no se finaliza automaticamente. 

por lo cual se solicita desactivar esa sesion. 

### Pasos para reproducir

ingresar al modulo de recepcion
ingresar usuario, contraseña  y modulo 
ingresar la cc y buscar

### Versión

1.3.220

**Comment by CJavierSaldana** [comment]
paciente revertido. se recomienda usar nuevo template para revertir sesiones disponible en 

https://github.com/MiFisico/mf-support/issues/new/choose

**Comment by mifisicoltda** [comment]
sr carlos este paciente no me sale revertido, me sale en estado finalizado y necesito es revertirlo, porque uno lo habian creado y el otro si es el correcto. 

![image](https://github.com/user-attachments/assets/f5313c06-2c22-41cd-a693-77b9ea178a04)

**Comment by CJavierSaldana** [comment]
listo, revertido. mil disculpas por la confusión.

**Comment by mifisicoltda** [comment]
gracias
