### ISSUE TITLE
[Error]: no muestra para escoger los ejercicios para planificar 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#26]
### ¿Qué sucedió?

se ingreso para planificar a la paciente cc: 22428954 MARIA GLADYS DIAZ PLATA  el 01 de noviembre pero no muestra la lista desplegable de los ejercicios. ver video. 

### Pasos para reproducir

https://github.com/user-attachments/assets/2fa9b328-b097-42a7-bc00-e41debc23ebb

### Versión

1.3.220

**Comment by CJavierSaldana** [comment]
tabla de ejercicisov2 fue restaurada en el ambiente de producción

**Comment by mifisicoltda** [comment]
Funciona correctamente, gracias
