### ISSUE TITLE
[Funcionalidad]: agregar una opcion donde el fisio y el medico deportologo puedan añadir su firma 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#29]
### ¿Tu solicitud está relacionada con algún problema?

se solicito agregar la información del fisio o medico deportologo tratante en las historias clinicas pero no se cuenta con el modulo para que los cargos en mención añadan su firma 

### Describe la solución que te gustaría

una opcion donde permita añadir la firma 

### Describe las alternativas que has considerado

añadir un boton en el  area de gerencia usuarios fisios y  habilitar un botonn que permita registrar la firma del fisio o medico deportologo 
![image](https://github.com/user-attachments/assets/c695599c-5ceb-4cf3-a558-5dcdc20a2b34)

**Comment by CJavierSaldana** [comment]
![image](https://github.com/user-attachments/assets/9016f6f5-0077-45ef-be7a-805a3fad36b3)

se ha agregado la funcionalidad de establecer la firma para el fisioterapeuta. Sí este no ha firmado, la HC saldrá sin firma

**Comment by mifisicoltda** [comment]
para añadir la firma me muestra esto
![image](https://github.com/user-attachments/assets/88e38ba5-d4ea-45b7-89ac-be6f758e5e59)
es un error ?

**Comment by CJavierSaldana** [comment]
si es un error. se me fue un parámetro mal. ya lo cambio

**Comment by CJavierSaldana** [comment]
Ya puedes revisar de nuevo

**Comment by mifisicoltda** [comment]
ya funciona correctamente, aprobado
