### ISSUE TITLE
[Error]: no se visualiza correctamente algunos campos de hc de terapia fisica 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#30]
### ¿Qué sucedió?

en la exportación de hc de terapia fisica integral no se visualizan correctamente los siguientes campos: 
![image](https://github.com/user-attachments/assets/2bc70b1b-e225-4124-a2ef-367a5ffaebc9)
en esta imagen lo que esta subrayado en color amarillo debe ir el nombre de la entidad
 
![image](https://github.com/user-attachments/assets/e63a5fc9-d313-4b13-be97-7d54bcc3b3fe)
en esta imagen lo que esta subrayado en color amarillo debe ir es la descripcion del diagnostico 

![image](https://github.com/user-attachments/assets/7114d7e3-761b-4059-87f1-4f1d39e591b5)
en esta imagen se debe mostrar correctamente la descripcion de los ejercicios 

![image](https://github.com/user-attachments/assets/9a10e109-3f99-44f3-9160-0c1beef5f6ba)
se debe  corregir la complejidad del paciente y el diagnostico debe mostrar es la descripcion 

### Pasos para reproducir

ingresar al modulo de fisioterapia escoger el resumen de hc e ingresra el numero de documento o nombre del paciente y dar doble clic o ingresando al modulo de recepcion opcion pacientes escoger el resumen de hc e ingresra el numero de documento o nombre del paciente y dar doble clic

### Versión

1.3.220

**Comment by CJavierSaldana** [comment]
ahora se están mostrando los campos de ejercicios con los valores correctos
