### ISSUE TITLE
[Error]: no exporta la informacion de medicina deportiva 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#32]
### ¿Qué sucedió?

![image](https://github.com/user-attachments/assets/91232344-5970-4c01-a25a-b1c754acaace)
se ingreso a visualizar la hc de medicina deportiva y nos muestra este error 

### Pasos para reproducir

ingresar a resumen de hc ingresar nombre o numero de documento y dar doble clic 

### Versión

1.3.220

**Comment by CJavierSaldana** [comment]
Puedes por favor indicar número de cédula, fecha y hora de atención de la persona que tiene el poblema ?

**Comment by mifisicoltda** [comment]
1040740643 fecha: 11/06/2024 hora: 6am 
3234731070 fecha: 11/06/2024 hora: 6am 
55302948 fecha: 11/06/2024 hora: 6am
8686391 fecha: 11/06/2024 hora: 6am

**Comment by CJavierSaldana** [comment]
Este error está corregido en la versión v1.4.52 de mf-historiaclinica. ver notas del arreglo

https://github.com/MiFisico/mf-support/releases/tag/assistreh-v1.1.1

**Comment by CJavierSaldana** [comment]
corregido

**Comment by mifisicoltda** [comment]
![image](https://github.com/user-attachments/assets/ea4e92e2-7f6b-42bf-83bf-6bd04125e2d2)
en la exportacion de hc solo muestra la informacion basica del paciente
