### ISSUE TITLE
[Funcionalidad]: Agregar cambios de planificación en hc pdf 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#34]
### ¿Tu solicitud está relacionada con algún problema?

cualquier cambio en la planificación debe generar una nueva hoja en el día que se haga la modificación.

### Describe la solución que te gustaría

en  todas las hc, agregar una nueva hoja con todos los valores de la planificación de la sesión donde se haya modificado.

**Comment by CJavierSaldana** [comment]
cada cambio por más pequeño qu esea a una planificación agregará la hoja completa de la fecha en la que la planificación se cambió
