### ISSUE TITLE
[Error]: REPORTE DE ERROR EN INTERFAZ DE MOVIMIENTO SIIGO 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#35]
### ¿Qué sucedió?

La empresa creada bajo el nombre H.D.I la crearon con nit: 860004875-6, pero generaba error al momento de exportar la información de movimiento siigo, lo que se hizo fue modificar el nit y se dejo de la siguiente forma: 860004875 pero cuando se genero nuevamente movimiento siigo se desaparecieron 18 registros de la exportación que están relacionado con esta empresa. 
 los pacientes en mención son: 
cc: 22578386 y cc: 7465858

### Pasos para reproducir

ingresar a gerencia, movimiento siigo, escoger el rango de fecha del 01 de octubre a 08 de noviembre y dar en buscar 
![image](https://github.com/user-attachments/assets/1825cab2-c7ad-45e5-a4c5-6e9543397018)
escoger la que se va a revisar y dar en exportar 

### Versión

1.3.220

**Comment by CJavierSaldana** [comment]
se aplicó conjunto de cambios para normalizar datos de la empresa mencionada. Los registros ahora están disponibles en `mocvon`
