### ISSUE TITLE
[Soporte]: REVERTIR PACIENTE GUILLERMO PUELLO

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#37]
### Número de cédula

8787865

### Fecha de la sesión

12/11/2024

### Hora de la sesión

6AM

### Motivo de la cancelación

Por favor revertir al paciente guillermo puello de articulos ortopedicos del 12/11/2024 de las 6am la sesion que no esta finalizada, ya que se creo mal el servicio.

**Comment by CJavierSaldana** [comment]
paciente revertido
