### ISSUE TITLE
[Error]:KARIME ARIZA CC 32.738.932

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#39]
### ¿Qué sucedió?

Paciente Karime Ariza cc 32.738.932 el dia 12/11/2024 hora 03:00pm se le registra abono de $33.200 pero en el cuadre de caja no aparece el abono y si revisamos por recibo de caja el ultimo abono registrado sale del 08/11/2024 por favor revisar. 

### Pasos para reproducir

revisar abono paciente Karime Ariza. 

### Versión

1

**Comment by CJavierSaldana** [comment]
recibo restaurado #282654
