### ISSUE TITLE
[Error]: error en la complejidad 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#4]
### ¿Qué sucedió?

los fisioterapeutas colocan una complejidad y el sistema esta colocando por defecto complejidad media a todo el que está siendo programado

### Pasos para reproducir

https://github.com/user-attachments/assets/68f1a8ab-4c17-499b-8941-f2e95ad396a9

https://github.com/user-attachments/assets/85642258-99d9-4c99-b6d9-8f7b8108dac7

### Versión

1.3.220

**Comment by CJavierSaldana** [comment]
Problema se presenta porque no se está estableciendo correctamente los valores de complejidad al guardar. entonces queda el valor por defecto. 

Se procede a modificar el guardado.

**Comment by CJavierSaldana** [comment]
En la primera sesión no hay forma de guardar en la historia clínica la complejidad. 

@mifisicoltda debería tener la primera sesión poder escoger la complejidad ?

**Comment by CJavierSaldana** [comment]
Se realizó los cambios necesarios para que, al momento de agendar una nueva cita desde el área de fisioterapia, este se lleve la complejidad establecida anteriormente.

**Comment by mifisicoltda** [comment]
revisad, funciona correctamente

**Comment by mifisicoltda** [comment]
se decidió en conjunto con carolina que prevalecerá  la complejidad y zona de atención puestos en la hoja de evolución de hc de terapia física.

**Comment by CJavierSaldana** [comment]
tomar la complejidad de planificación de primera sesión de referencia para la segunda sesión.
