### ISSUE TITLE
[Error]:CARLINA NAVARRO 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#40]
### ¿Qué sucedió?

Paciente carlina navarro cc 22443311 de 1pm del dia 13/11/2024 atendida por el fisioterapeuta juan triviño, no le deje llenar la historia clinica, cuando da doble clic sobre la cita le sale un error que adjunto. 

### Pasos para reproducir

![PHOTO-2024-11-13-13-14-35](https://github.com/user-attachments/assets/8dc39c6a-0aa6-4608-9d71-425f3a64feb8)

### Versión

1

**Comment by CJavierSaldana** [comment]
problema de la fecha de nacimiento se arregló y se evitó problema
