### ISSUE TITLE
[Soporte]: LEVIS HERRERA

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#41]
### Número de cédula

22732612

### Fecha de la sesión

13/11/2024

### Hora de la sesión

6AM

### Motivo de la cancelación

por favor revertir la sesión de la Sra. Levis Herrera, ya que es un articulo ortopédico y fue creado como terapia física, gracias.

**Comment by CJavierSaldana** [comment]
revertido
