### ISSUE TITLE
[Error]: no cargan la firma de manera correcta

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#42]
### ¿Qué sucedió?

![image](https://github.com/user-attachments/assets/38973f0a-7bd0-4c66-a625-1a9f181a1c87)
en las anteriores sesiones al dia que se realizo el registro de la firma del fisio o medico deportologo, sale una firma por defecto que no corresponde a nadie 

### Pasos para reproducir

ingresar a la opcion resumen de hc ingresar numero de documento o nombre del paciente dar en buscar y visualizar 

### Versión

1.3.223

**Comment by CJavierSaldana** [comment]
Ahora la evolución incluye la misma firma que el documento de finalización de historia clínica
