### ISSUE TITLE
[Error]: se quiere abrir la sesion de un paciente y se abre otro 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#43]
### ¿Qué sucedió?

el fisio  ingreso al modulo de fisioterapia y esta intentando evolucionar a un paciente nueva orden y muestra es la informacion de otra persona 

https://github.com/user-attachments/assets/aef37c52-c1af-4e56-baef-be5dc7d3ce6b

### Pasos para reproducir

ingresar al modulo de fisioterapia 
escoger el dia 20/11/2024
el paciente esta ubicado en el giimnasio 6 a las 10am con el fisioterapeuta juan triviño 

### Versión

1.3.223

**Comment by CJavierSaldana** [comment]
Se cambió la orden que tenía. Actualmente tenía una orden que correspondía a otra persona. Se modificó en producción y ahora muestra la información correcta
