### ISSUE TITLE
[Error]: DILIGENCIAR UNA HC MUESTRA UN MENSAJE DE ERROR

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#44]
### ¿Qué sucedió?

SE INICIO LA ATENCION DEL PACIENTE CC:72271573 EL DIA 23 DE NOVIEMBRE Y CUANDO EL FISIO VA A DILIGENCIAR LA HC MUESTRA EL SIGUIENTE ERROR EL SIGUIENTE ERROR
![image](https://github.com/user-attachments/assets/805137fe-3867-4846-a56a-5961fbd93630)

### Pasos para reproducir

INGRESAR AL MODULO DE FISIOTERAPEUTAS 
INGRESAR EL USUARIO 
ESCOGER EL DIA 23 DE NOVIEMBRE
 Y SELECCIONAR AL PACIENTE QUE ESTA EN GIMNASIO 5 A LAS 9AM

### Versión

1.3.223

**Comment by CJavierSaldana** [comment]
se liberó una nueva versión que evita que salga de nuevo este error
