### ISSUE TITLE
[Error]: ERROR AL ABRIR Y EXPORTAR UNA HC DE MEDICINA DEPORTIVA

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#45]
### ¿Qué sucedió?

EL DOCTOR DILIGENCIO LA HC DEL PACIENTE CC: 1043605725
PERO AHORA MUESTRA LO SIGUIENTE CUANDO SE INTENTO ABRIR DE NUEVO 
![image](https://github.com/user-attachments/assets/46da50f3-e105-48ff-80fe-1855ef280f89)
Y CUANDO SE VA A EXPORTAR EL RESUMEN DE HISTORIA CLINICA DEL PACIENTE EN MENCION SALE LO SIGUEINTE 

![image](https://github.com/user-attachments/assets/0a257c9a-a6df-4a29-bf1e-35733fda129d)

SOLO ME SUCEDIO CON EL PACIENTE 

### Pasos para reproducir

ENTRAR AL MODULO DE FISIOTERAPIA Y DAR CLIC SOBRE EL PACIENTE PARA INTENTAR ABRIR LA HC O DARLE CLIC EN RESUMEN DE HISTORIA CLINICA PARA LA VISUALIZACION 

### Versión

1.3.223

**Comment by CJavierSaldana** [comment]
historia corregida.
