### ISSUE TITLE
[Soporte]: NO HIZO LA TERAPIA EN PISCINA POR LLUVIA Y SE ACABABA DE REALIZAR 1 EN GIMNASIO

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#46]
### Número de cédula

84083799

### Fecha de la sesión

27/11/2024

### Hora de la sesión

3PM

### Motivo de la cancelación

ESTABA LLOVIENDO EL PACIENTE NO QUISO INGRESAR A PISCINA Y NO SE REALIZO GIMNASIO PORQUE EL ACABABA DE TERMINAR UNA A LAS 2PM EN GIMNASIO.

**Comment by CJavierSaldana** [comment]
se canceló el paciente para poder resolver el issue https://github.com/MiFisico/mf-support/issues/48
