### ISSUE TITLE
[Error]: no podemos editar el numero de documento de un paciente 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#47]
### ¿Qué sucedió?

se esta intentando modificar al paciente PA: 21}85831
![image](https://github.com/user-attachments/assets/6b127d2d-25be-42da-ae62-88f1fab2ba03)

CUANDO SE ABRE AL PACIENTE NO MUESTRA LA INFORMACION, SE QUEDA ASI: 
![image](https://github.com/user-attachments/assets/d51084c7-785d-4128-a692-0e24fe234816)
 NECESITAMOS BORRAR EL CORCHETE QUE ESTA EN MEDIO DEL NUMERO DE DOCUMENTO 

### Pasos para reproducir

INGRESAR A LISTADO DE PACIENTE 
E INGRESAR EL NUMERO DE DOCUMENTO PA: 21}85831

### Versión

1.3.223

**Comment by CJavierSaldana** [comment]
paciente corregido.
