### ISSUE TITLE
[Error]: NO SE PUEDE EVOLUCIONAR AL PACIENTE CC: 84083799

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#48]
### ¿Qué sucedió?

SE ESTA INTENTANDO EVOLUCIONAR AL PACIENTE CC: 84083799 UBICADO EL DIA 28 DE NOVIEMBRE EN GIMNASIO GIMNASIO 8 A LAS 9AM 
MUESTRA LO SIGUIENTE CUANDO SE ESTA INTENTANDO  EVOLUCIONAR 
![image](https://github.com/user-attachments/assets/c26f734e-dcd5-45f8-8d9a-86e9cb2dc3e3)

### Pasos para reproducir

INGRESAR AL MODULO DE FISIOTERAPIA 
INGRESAR LAS CREDENCIALES DEL FISIO 
E INTENTAR EVOLUCIONAR AL PACIENTE 

### Versión

1.3.223

**Comment by CJavierSaldana** [comment]
No se pueden tener dos sesión pendiente por cerrar y tratar de continuar otra con la misma orden. se cerró la sesión a solicitud https://github.com/MiFisico/mf-support/issues/46 y ahora funciona correctamente
