### ISSUE TITLE
[Funcionalidad]: añadir informacion del medico  deportologo y del fisio en la exportacion de hc 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#5]
### ¿Tu solicitud está relacionada con algún problema?

se solicita añadir en las historias de medicina deportiva, terapia fisica y acondicionamiento la firma del fisio o medico deportologo, nombre y el tipo y numero de documento 

### Describe la solución que te gustaría

en la exportacion de las historias clinicas

**Comment by mifisicoltda** [comment]
esta informacion la debe mostrar por cada vez que el paciente sea atendido, es decir que por cada atencion debe mostrar  la firma del fisio o medico deportologo, nombre y el tipo y numero de documento.

**Comment by CJavierSaldana** [comment]
Es necesario crear un nuevo tiquete ya que los fisioterapeutas deberán agregar su firma en algún lugar el cuál no ha sido discutido. 

Require revisión contractual.

**Comment by mifisicoltda** [comment]
revisado, se procedera a crear el nuevo tiquete
