### ISSUE TITLE
[Error]: No esta incluyendo toda la informacion de las hc en la exportacion 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#7]
### ¿Qué sucedió?

cuando se va a descargar o visualizar cualquiera de las 3 historias no esta incluyendo toda la información solo se visualiza la informacion general de la IPS, informacion del paciente y el motivo. 

se solicita añadir toda la informacion segun los modelos suministrados 
[ejemplos de exportacion medicina deportiva.pdf](https://github.com/user-attachments/files/17563264/ejemplos.de.exportacion.medicina.deportiva.pdf)
[ejemplos de exportacion HC DE TERAPIA FISICA.pdf](https://github.com/user-attachments/files/17563266/ejemplos.de.exportacion.HC.DE.TERAPIA.FISICA.pdf)

### Pasos para reproducir

ingresar a la opcion de resumen de historia clinica
ingresar el nombre o el numero de documento y seleccionar la orden que se quiere visualizar o exportar 

### Versión

1.3.220

**Comment by mifisicoltda** [comment]
En la exportación de la hc clínica se debe incluir la valoración de la zona afectada, la planificación de tratamiento y pestaña de evolución y en algún momento dado si tiene diligenciado la pestaña de pruebas también incluirla

**Comment by CJavierSaldana** [comment]
solucionado con https://github.com/MiFisico/mf-support/issues/5

**Comment by mifisicoltda** [comment]
la exportacion de acondicionamiento me sale con este error: 
![image](https://github.com/user-attachments/assets/7e9e7aa2-1803-4ffb-acb8-38fc74b5c429)

en la exportacion de la hc de medicina deportiva me sale este error

![image](https://github.com/user-attachments/assets/e8ae2e9f-3a7e-410d-b65f-c465c0a57732)

**Comment by mifisicoltda** [comment]
Hola sr carlos probando nuevamente me sigue saliendo lo adjuntado en las imagenes anteriores

**Comment by CJavierSaldana** [comment]
se reabre por inconsistencia en staging

**Comment by CJavierSaldana** [comment]
corregido
