### ISSUE TITLE
[Error]: error en la visualizacion de calendario en fecha de lesion y fecha de procedimiento 

### ISSUE THREAD

**Issue by mifisicoltda** [MiFisico/mf-support#8]
### ¿Qué sucedió?

cuando se va a escoger el mes y el año anteriores al 2024 no se visualiza correctamente el calendario por lo tanto toca ir mes por mes para poder escoger la fecha indicada 
![image](https://github.com/user-attachments/assets/97c7e4b9-13b5-41af-b1ce-1b39f3bbeaa2)

### Pasos para reproducir

ingresar a 1era sesion del paciente activo 
en la parte de fecha de lesion o fecha de procedimiento escoger calendario 

### Versión

1.3.220

**Comment by CJavierSaldana** [comment]
El componente no es compatible con un zoom por debajo del 100%. se recomienda usar el zoom por defecto del navegador que es 100%. se adjunta vídeo que muestra cómo se puede realizar. 

https://github.com/user-attachments/assets/17be8dbf-24c0-48b6-a631-5722bcbde741

**Comment by mifisicoltda** [comment]
ok gracias. revisado
